"""Global Constants"""

# HTTP Status Codes
SUCCESS_CODE = 200
ACCEPTED_CODE = 202
NO_CONTENT_CODE = 204
BAD_REQUEST = 400
NOT_FOUND = 404

# Key Value Constants
COMPLETED = "Completed"
ERROR = "Error encountered: {error}"
FAILED = "Failed"
INPROGRESS = "In-Progress"
INSERT = "insert"
INVALID_TASK_ID = "Task {id} not valid"
SQLALCHEMY_ECHO_KEY = "SQLALCHEMY_ECHO"
SQLALCHEMY_DATABASE_URI_KEY = "SQLALCHEMY_DATABASE_URI"
SQLALCHEMY_TRACK_MODIFICATIONS_KEY = "SQLALCHEMY_TRACK_MODIFICATIONS"
SWAGGER_FILE_NAME = "openapi.yml"
TASK_STATUS_KEY = "task_status"
TASK_ERROR_KEY = "task_error"
UPDATE = "update"
