openapi: 3.0.8
info:
  title: '{{title}}'
  version: '1.0'

paths:
 /task/{task_id}:
   parameters:
     - name: task_id
       in: path
       description: Task id to get status of task
       required: true
       schema:
         type: string
   get:
     operationId: "views.asyncworker.get_status"
     tags:
       - "Jobs"
     summary: "Get job status"
     description: "Get job status"
     responses:
       200:
         description: Return status of the job
       400:
         description: There was an error with the parameters passed to this API call
       404:
         description: A task with the specified id was not found.
       500:
         description: Error encountered

 /topics:
   get:
     operationId: "views.topics.get_all"
     tags:
       - "Topics"
     summary: "List Topics"
     description: "List all the topics"
     responses:
       200:
         description: "List all topics with categories"
         content:
           application/json:
             schema:
               type: object

 /topics/{name}:
   parameters:
     - name: name
       in: path
       description: The topic name.
       required: true
       schema:
         type: string
   get:
     operationId: "views.topics.get_by_name"
     tags:
       - "Topics"
     summary: "Get By Name"
     description: "Get topics by name"
     responses:
       200:
         description: "Get topic details by name"
         content:
           application/json:
             schema:
               type: object
       400:
         description: There was an error with the parameters passed to this API call
       500:
         description: Error encountered
   put:
     operationId: "views.topics.update_by_name"
     tags:
       - "Topics"
     summary: "Update Topic"
     description: "Update topic name"
     responses:
       200:
         description: Successfully updated the name in topics list
       400:
         description: There was an error with the parameters passed to this API call
       404:
         description: A topic with the specified nme was not found.
       405:
         description: This operation is not supported for privileged user
       500:
         description: Error encountered
   delete:
     operationId: "views.topics.delete_by_name"
     tags:
       - "Topics"
     summary: "Delete Topic With Name"
     description: "Delete Topic With Specific Name"
     responses:
       200:
         description: Successfully deleted a name from topics list
       400:
         description: There was an error with the parameters passed to this API call
       404:
         description: A topic with the specified name was not found.
       405:
         description: This operation is not supported for privileged user
       500:
         description: Error encountered

#servers:
#  - url: http://127.0.0.1:5000/v1/