openapi: 3.0.8
info:
  title: '{{title}}'
  version: '1.0'

paths:
 /task/{task_id}:
   parameters:
     - name: task_id
       in: path
       description: Get the status of task with ID
       required: true
       schema:
         type: string
   get:
     operationId: "views.tasks.get_status"
     tags:
       - "Jobs"
     summary: "Get Task Status"
     description: "Get task status"
     responses:
       200:
         description: Return status of the task
       400:
         description: There was an error with the parameters passed to this API call
       404:
         description: A task with the specified ID was not found.
       500:
         description: Error encountered

 /topics:
   get:
     operationId: "views.topics.get_all"
     tags:
       - "Topics"
     summary: "List Topics"
     description: "List all the topics"
     responses:
       200:
         description: "List topics with categories"
         content:
           application/json:
             schema:
               type: object

 /topics/{name}:
   parameters:
     - name: name
       in: path
       description: The topic name.
       required: true
       schema:
         type: string
   get:
     operationId: "views.topics.get_by_name"
     tags:
       - "Topics"
     summary: "Get By Topic Name"
     description: "Get By Topic Name"
     responses:
       200:
         description: "Get topic details by name"
         content:
           application/json:
             schema:
               type: object
       202:
         description: Request has been accepted for inserting the topic
       400:
         description: There was an error with the parameters passed to this API call
       500:
         description: Error encountered
   put:
     operationId: "views.topics.update_by_name"
     tags:
       - "Topics"
     summary: "Update Topic Details"
     description: "Update Topic Details"
     responses:
       202:
         description: Request has been accepted for updating the categories
       400:
         description: There was an error with the parameters passed to this API call
       404:
         description: A topic with the specified name was not found.
       405:
         description: This operation is not supported for privileged user
       500:
         description: Error encountered
   delete:
     operationId: "views.topics.delete_by_name"
     tags:
       - "Topics"
     summary: "Delete Topic With Name"
     description: "Delete Topic With Name"
     responses:
       204:
         description: Successfully deleted a name from topics list
       400:
         description: There was an error with the parameters passed to this API call
       404:
         description: A topic with the specified name was not found.
       405:
         description: This operation is not supported for privileged user
       500:
         description: Error encountered
